spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: mdd-api
  datasource:
    url: jdbc:mysql://localhost:3307/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
